package com.example.entity;

import java.lang.Long;
import java.lang.String;
import java.sql.Timestamp;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by javapeot
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Config {
    @Id
    @GeneratedValue(
            strategy = GenerationType.IDENTITY
    )
    private Long id;

    private String name;

    private String description;

    private Timestamp createdAt;
}
